apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: microservices-photogallery
deploy:
  kubectl: 
    manifests: 
      - ./k8s/*
build:
  googleCloudBuild: 
    projectId: forward-dream-436005-g7
  artifacts:
    - image: gcr.io/forward-dream-436005-g7/eventbusserv
      context: MicroServices/EventBusServ
      sync: 
        manual:
          - src: "*"
            dest: .
    - image: gcr.io/forward-dream-436005-g7/gallerymgmtserv
      context: MicroServices/GalleryMgmtServ
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src: "*"
            dest: .
    - image: gcr.io/forward-dream-436005-g7/loggingserv
      context: MicroServices/loggingServ
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src: "*"
            dest: .
    - image: gcr.io/forward-dream-436005-g7/queryserv
      context: MicroServices/QueryServ
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src: "*"
            dest: .
    - image: gcr.io/forward-dream-436005-g7/storagemgmtserv
      context: MicroServices/StorageMgmtServ
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src: "*"
            dest: .
    - image: gcr.io/forward-dream-436005-g7/usagemntrserv
      context: MicroServices/UsageMntrServ
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src: "*"
            dest: .
    - image: gcr.io/forward-dream-436005-g7/useraccmgmtserv
      context: MicroServices/UserAccMgmtServ
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src: "*"
            dest: .